name: "make4ht-action"
author: "Michal Hoftich"
description: "Convert TeX documents to XML using make4ht"
inputs:
  command:
    description: "Direct make4ht command"
    required: true
  extra_packages:
    description: "Extra packages installed using apt-get"
    required: false
  output_dir:
    description: "Output directory for the HTML files"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    command: ${{ inputs.command }}
    extra-packages: ${{ inputs.extra-packages }}



